
FROM atoml/java AS android-sdk

MAINTAINER marmotcai "marmotcai@163.com"

ENV WORK_DIR /opt

#################################################################################################

# Install Android SDK.

RUN dpkg --add-architecture i386 && \
    apt -qq update && \
    apt -qq install -y wget curl maven ant gradle libncurses5:i386 libstdc++6:i386 zlib1g:i386 python-software-properties 

ENV ANDROID_SDK_URL="https://dl.google.com/android/repository/tools_r25.2.5-linux.zip" \
    ANDROID_BUILD_TOOLS_VERSION=28.0.3 \
    ANDROID_APIS="android-17,android-24,android-25,android-26,android-27,android-28" \
    ANT_HOME="/usr/share/ant" \
    MAVEN_HOME="/usr/share/maven" \
    GRADLE_HOME="/usr/share/gradle" \
    ANDROID_HOME="$WORK_DIR/android/sdk"

ENV PATH $PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION:$ANT_HOME/bin:$MAVEN_HOME/bin:$GRADLE_HOME/bin

WORKDIR $WORK_DIR

# Installs Android SDK
RUN mkdir -p $ANDROID_HOME && cd $ANDROID_HOME && \
    wget -O tools.zip ${ANDROID_SDK_URL} && \
    unzip tools.zip && rm tools.zip

RUN echo y | android update sdk -a -u -t platform-tools,${ANDROID_APIS},build-tools-${ANDROID_BUILD_TOOLS_VERSION} && \
    chmod a+x -R $ANDROID_HOME && \
    chown -R root:root $ANDROID_HOME

 # Clean up
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoremove -y && \
    apt-get clean

#################################################################################################

FROM atoml/android-sdk AS android-ndk

ENV WORK_DIR /opt

WORKDIR $WORK_DIR

# Install Android NDK.
ENV	ANDROID_NDK_URL="https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip" \
	ANDROID_NDK_HOME="$ANDROID_HOME/android-ndk-r16b" \
	ANDROID_TOOLCHAIN_HOME="$ANDROID_HOME/toolchain_android/aarch64"

# Installs Android NDK
RUN wget -O ndk.zip ${ANDROID_NDK_URL} && \
	unzip ndk.zip -d $ANDROID_HOME && rm -f ndk.zip

# RUN echo y | android update sdk --no-ui --all --filter build-tools-24.0.3 && \
#     echo y | android update sdk --no-ui --all --filter android-24

RUN mkdir -p $ANDROID_TOOLCHAIN_HOME
RUN $ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh --platform=android-24 --install-dir=$ANDROID_TOOLCHAIN_HOME --arch=arm64 --force

# Update PATH for the above.
ENV PATH $PATH:$ANDROID_TOOLCHAIN_HOME/bin

#################################################################################################
