FROM marmotcai/golang AS golang-builder

ENV APP_GIT_URL="https://github.com/minio/minio"
ENV APP_PATH=$GOPATH/src/github.com/minio

RUN mkdir -p $APP_PATH

WORKDIR $APP_PATH

RUN git clone $APP_GIT_URL
RUN cd minio && \
    go install
    
#RUN gopm bin
#RUN gopm clean
#COPY golang/build.sh $GOBIN/build
#RUN wget -O $GOBIN/build https://raw.githubusercontent.com/marmotcai/gather/master/golang/build.sh
#RUN chmod +x $GOBIN/build
#VOLUME ["/root/output"]
#WORKDIR /root
#CMD ["build"]

