FROM marmotcai/centos-base AS golang-base

MAINTAINER marmotcai "marmotcai@163.com"

ENV GOLANG_VERSION 1.11.1
ENV WORK_DIR /usr/local
ENV GOROOT $WORK_DIR/go
ENV GOPATH /root/go
ENV PATH $PATH:$GOROOT/bin:$GOPATH/bin

RUN curl https://dl.google.com/go/go$GOLANG_VERSION.linux-amd64.tar.gz | tar xz -C $WORK_DIR && \
        mkdir -p $GOPATH

RUN go version

WORKDIR $GOPATH

RUN go get -u github.com/gpmgo/gopm

