FROM marmotcai/centos-base AS ceph-deploy
MAINTAINER marmotcai "marmotcai@163.com"

ADD ceph/ceph.repo /etc/yum.repos.d/ceph.repo

RUN yum clean all && \
        yum makecache fast

# RUN yum install -y subscription-manager # && \
#       subscription-manager repos --enable=rhel-7-server-extras-rpms && \
#       yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum update -y && sudo yum install -y sshpass ceph-deploy.noarch
# RUN yum install -y http://mirrors.163.com/ceph/rpm-jewel/el7/noarch/ceph-deploy-1.5.39-0.noarch.rpm
RUN ceph-deploy --version

ENV WORK_DIR=/root
WORKDIR $WORK_DIR

# RUN ssh-keygen -y -t rsa -f /etc/ssh/ssh_host_rsa_key
# RUN ssh-keygen -y -t dsa -f /etc/ssh/ssh_host_dsa_key
CMD /usr/sbin/sshd -D

# ADD ceph/script/entrypoint.sh .
# ENTRYPOINT ["entrypoint.sh"]
