FROM marmotcai/centos-base AS ceph-deploy
MAINTAINER marmotcai "marmotcai@163.com"

RUN yum clean all && \
        rm -rf /etc/yum.repos.d/*.repo && \
        wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
        wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo

RUN sed -i '/aliyuncs/d' /etc/yum.repos.d/CentOS-Base.repo && \
        sed -i 's/$releasever/7/g' /etc/yum.repos.d/CentOS-Base.repo && \
        sed -i '/aliyuncs/d' /etc/yum.repos.d/epel.repo

RUN yum clean all && \
        yum makecache fast

RUN yum update -y && sudo yum install -y ceph-deploy vim sshpass
RUN yum install http://mirrors.163.com/ceph/rpm-jewel/el7/noarch/ceph-deploy-1.5.38-0.noarch.rpm
RUN ceph-deploy --version

ENV WORK_DIR=/root
WORKDIR $WORK_DIR

# ADD ceph/script/entrypoint.sh .
# ENTRYPOINT ["entrypoint.sh"]
