FROM marmotcai/centos-base AS nfs
MAINTAINER marmotcai "marmotcai@163.com"

RUN yum clean all && \
        yum makecache fast

RUN yum update -y && sudo yum install -y nfs-utils

ENV WORK_DIR=/root
WORKDIR $WORK_DIR

