FROM marmotcai/java AS nodejs

ENV NODEJS_VERSION=8.15.0 \
    PATH=$PATH:/opt/node/bin

WORKDIR "/opt/node"

RUN apt-get update && apt-get install -y curl git ca-certificates --no-install-recommends
RUN rm -rf /var/lib/apt/lists/* && apt-get clean

RUN wget https://nodejs.org/dist/v${NODEJS_VERSION}/node-v${NODEJS_VERSION}-linux-x64.tar.gz
RUN tar xvf node-v${NODEJS_VERSION}-linux-x64.tar.gz --strip-components=1
RUN rm -f node-v${NODEJS_VERSION}-linux-x64.tar.gz
